### ISSUE TITLE
Can it resolve those kind of images?

### ISSUE THREAD

**Issue by ghost** [Kagami/chaptcha#3]
![vb7](https://cloud.githubusercontent.com/assets/4132665/19020649/62c7679c-88d9-11e6-901f-6cd7ee9bf39a.JPG)
![vb8](https://cloud.githubusercontent.com/assets/4132665/19020650/62c89162-88d9-11e6-821d-49c59c694d32.JPG)
![vb9](https://cloud.githubusercontent.com/assets/4132665/19020654/62c9e922-88d9-11e6-906e-b8da1da97c16.JPG)
![vb2](https://cloud.githubusercontent.com/assets/4132665/19020653/62c9a48a-88d9-11e6-8bbb-3013bfffbb52.JPG)
![vb3](https://cloud.githubusercontent.com/assets/4132665/19020652/62c992d8-88d9-11e6-8f2f-385b29d06f5c.JPG)
![vb4](https://cloud.githubusercontent.com/assets/4132665/19020651/62c94080-88d9-11e6-96b8-f16395dc5bdf.JPG)
![vb5](https://cloud.githubusercontent.com/assets/4132665/19020655/62f4fd56-88d9-11e6-8197-baa981cde4fe.JPG)
![vb6](https://cloud.githubusercontent.com/assets/4132665/19020656/62f62e2e-88d9-11e6-8831-6a506b820dfd.JPG)

**Comment by Kagami** [comment]
No. Need to adjust preprocessing and segmentation routines for that.
